CREATE DATABASE projetos
WITH OWNER = postgres
     ENCODING = 'UTF-8'
     LC_COLLATE = 'Portuguese_Brazil.1252'
     LC.CTYPE='Portuguese_Brazil.1252'
     TABLESPACE=pg_default
     CONNECTION LIMIT = -1;

CREATE SCHEMA hotel;

DROP TABLE IF EXISTS hotel.USUARIO;

DROP TABLE IF EXISTS hotel.SUITE;

DROP TABLE IF EXISTS hotel.HOSPEDAGEM;

CREATE TABLE hotel.USUARIO (
	IDUSUARIO BIGSERIAL NOT NULL,
	NOME CHARACTER VARYING(150) NOT NULL,
	EMAIL CHARACTER VARYING(150) NOT NULL,
	SENHA CHARACTER VARYING(20) NOT NULL,
	IDADE INTEGER NOT NULL
);

ALTER TABLE hotel.USUARIO
ADD CONSTRAINT IDUSUARIO_PK PRIMARY KEY (EMAIL);

CREATE TABLE hotel.SUITE (
	IDSUITE BIGSERIAL NOT NULL,
	NOMESUITE CHARACTER VARYING(150) NOT NULL,
	STATUSQUARTO CHARACTER VARYING(7) CHECK (STATUSQUARTO IN ('VAGO', 'OCUPADO')) DEFAULT 'VAGO',
	EMAIL CHARACTER VARYING(150) NOT NULL
);

ALTER TABLE hotel.SUITE
ADD CONSTRAINT IDSUITE_PK PRIMARY KEY (IDSUITE);

ALTER TABLE hotel.SUITE
ADD CONSTRAINT IDUSUARIO_FK FOREIGN KEY (EMAIL) REFERENCES hotel.USUARIO (EMAIL);

CREATE TABLE hotel.HOSPEDAGEM (
	IDHOSPEDAGEM BIGSERIAL NOT NULL,
	DATAHOSPEDAGEM_INI DATE DEFAULT NOW(),
	DATAHOSPEDAGEM_FIM DATE NOT NULL,
	EMAIL CHARACTER VARYING(150) NOT NULL,
	IDSUITE BIGINT NOT NULL
);

ALTER TABLE hotel.HOSPEDAGEM
ADD CONSTRAINT IDHOSPEDAGEM_PK PRIMARY KEY (IDHOSPEDAGEM);

ALTER TABLE hotel.HOSPEDAGEM
ADD CONSTRAINT IDUSUARIO_FK FOREIGN KEY (EMAIL) REFERENCES hotel.USUARIO(EMAIL);

ALTER TABLE hotel.HOSPEDAGEM
ADD CONSTRAINT IDSUITE_FK FOREIGN KEY (IDSUITE) REFERENCES hotel.SUITE(IDSUITE);

